// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListAPI.Model.Context;

#nullable disable

namespace PasqualiSolution.API.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20240209150726_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDoListAPI.Model.RegisterPF", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BIrthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthDate");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("cpf");

                    b.Property<decimal>("IncomeValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("incomeValue");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("RegisterPF");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BIrthDate = new DateTime(2024, 2, 9, 12, 7, 25, 810, DateTimeKind.Local).AddTicks(5150),
                            Cpf = "14323412383",
                            IncomeValue = 3000m,
                            Name = "Teste PasqualiSolution"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
